//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsReniec
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReniecPersona_Request", Namespace="http://schemas.datacontract.org/2004/07/APP.GSWEE.Entidades")]
    public partial class ReniecPersona_Request : object
    {
        
        private string ClaveField;
        
        private string NumeroDeDocumentoField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave
        {
            get
            {
                return this.ClaveField;
            }
            set
            {
                this.ClaveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDeDocumento
        {
            get
            {
                return this.NumeroDeDocumentoField;
            }
            set
            {
                this.NumeroDeDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReniecPersona_Response", Namespace="http://schemas.datacontract.org/2004/07/APP.GSWEE.Entidades")]
    public partial class ReniecPersona_Response : object
    {
        
        private string CodigoField;
        
        private string MensajeField;
        
        private WsReniec.ReniecPersona_Registro PersonaDatoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WsReniec.ReniecPersona_Registro PersonaDato
        {
            get
            {
                return this.PersonaDatoField;
            }
            set
            {
                this.PersonaDatoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReniecPersona_Registro", Namespace="http://schemas.datacontract.org/2004/07/APP.GSWEE.Entidades")]
    public partial class ReniecPersona_Registro : object
    {
        
        private string ApellidoCasadaField;
        
        private string ApellidoMaternoField;
        
        private string ApellidoPaternoField;
        
        private string DireccionDomicilioField;
        
        private string DistDomicilioField;
        
        private string DptoDomicilioField;
        
        private string FechaNacimientoField;
        
        private string NombresField;
        
        private string NumeroDocumentoField;
        
        private string ProvDomicilioField;
        
        private string SexoField;
        
        private string UbigeoDistDomicilioField;
        
        private string UbigeoDptoDomicilioField;
        
        private string UbigeoProvDomicilioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoCasada
        {
            get
            {
                return this.ApellidoCasadaField;
            }
            set
            {
                this.ApellidoCasadaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno
        {
            get
            {
                return this.ApellidoMaternoField;
            }
            set
            {
                this.ApellidoMaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno
        {
            get
            {
                return this.ApellidoPaternoField;
            }
            set
            {
                this.ApellidoPaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionDomicilio
        {
            get
            {
                return this.DireccionDomicilioField;
            }
            set
            {
                this.DireccionDomicilioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistDomicilio
        {
            get
            {
                return this.DistDomicilioField;
            }
            set
            {
                this.DistDomicilioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DptoDomicilio
        {
            get
            {
                return this.DptoDomicilioField;
            }
            set
            {
                this.DptoDomicilioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumento
        {
            get
            {
                return this.NumeroDocumentoField;
            }
            set
            {
                this.NumeroDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProvDomicilio
        {
            get
            {
                return this.ProvDomicilioField;
            }
            set
            {
                this.ProvDomicilioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo
        {
            get
            {
                return this.SexoField;
            }
            set
            {
                this.SexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UbigeoDistDomicilio
        {
            get
            {
                return this.UbigeoDistDomicilioField;
            }
            set
            {
                this.UbigeoDistDomicilioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UbigeoDptoDomicilio
        {
            get
            {
                return this.UbigeoDptoDomicilioField;
            }
            set
            {
                this.UbigeoDptoDomicilioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UbigeoProvDomicilio
        {
            get
            {
                return this.UbigeoProvDomicilioField;
            }
            set
            {
                this.UbigeoProvDomicilioField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsReniec.IReniecPersona_Servicio")]
    public interface IReniecPersona_Servicio
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReniecPersona_Servicio/ConsultarPorNumeroDeDocumento", ReplyAction="http://tempuri.org/IReniecPersona_Servicio/ConsultarPorNumeroDeDocumentoResponse")]
        WsReniec.ConsultarPorNumeroDeDocumentoResponse ConsultarPorNumeroDeDocumento(WsReniec.ConsultarPorNumeroDeDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReniecPersona_Servicio/ConsultarPorNumeroDeDocumento", ReplyAction="http://tempuri.org/IReniecPersona_Servicio/ConsultarPorNumeroDeDocumentoResponse")]
        System.Threading.Tasks.Task<WsReniec.ConsultarPorNumeroDeDocumentoResponse> ConsultarPorNumeroDeDocumentoAsync(WsReniec.ConsultarPorNumeroDeDocumentoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorNumeroDeDocumento", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarPorNumeroDeDocumentoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WsReniec.ReniecPersona_Request peticion;
        
        public ConsultarPorNumeroDeDocumentoRequest()
        {
        }
        
        public ConsultarPorNumeroDeDocumentoRequest(WsReniec.ReniecPersona_Request peticion)
        {
            this.peticion = peticion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorNumeroDeDocumentoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarPorNumeroDeDocumentoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WsReniec.ReniecPersona_Response ConsultarPorNumeroDeDocumentoResult;
        
        public ConsultarPorNumeroDeDocumentoResponse()
        {
        }
        
        public ConsultarPorNumeroDeDocumentoResponse(WsReniec.ReniecPersona_Response ConsultarPorNumeroDeDocumentoResult)
        {
            this.ConsultarPorNumeroDeDocumentoResult = ConsultarPorNumeroDeDocumentoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IReniecPersona_ServicioChannel : WsReniec.IReniecPersona_Servicio, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ReniecPersona_ServicioClient : System.ServiceModel.ClientBase<WsReniec.IReniecPersona_Servicio>, WsReniec.IReniecPersona_Servicio
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ReniecPersona_ServicioClient() : 
                base(ReniecPersona_ServicioClient.GetDefaultBinding(), ReniecPersona_ServicioClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IReniecPersona_Servicio.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReniecPersona_ServicioClient(EndpointConfiguration endpointConfiguration) : 
                base(ReniecPersona_ServicioClient.GetBindingForEndpoint(endpointConfiguration), ReniecPersona_ServicioClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReniecPersona_ServicioClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ReniecPersona_ServicioClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReniecPersona_ServicioClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ReniecPersona_ServicioClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReniecPersona_ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public WsReniec.ConsultarPorNumeroDeDocumentoResponse ConsultarPorNumeroDeDocumento(WsReniec.ConsultarPorNumeroDeDocumentoRequest request)
        {
            return base.Channel.ConsultarPorNumeroDeDocumento(request);
        }
        
        public System.Threading.Tasks.Task<WsReniec.ConsultarPorNumeroDeDocumentoResponse> ConsultarPorNumeroDeDocumentoAsync(WsReniec.ConsultarPorNumeroDeDocumentoRequest request)
        {
            return base.Channel.ConsultarPorNumeroDeDocumentoAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IReniecPersona_Servicio))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IReniecPersona_Servicio))
            {
                return new System.ServiceModel.EndpointAddress("http://app_pruebas.midis.gob.pe/Sis_WS/App/ReniecPersona_Servicio.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ReniecPersona_ServicioClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IReniecPersona_Servicio);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ReniecPersona_ServicioClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IReniecPersona_Servicio);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IReniecPersona_Servicio,
        }
    }
}
