// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MIDIS.SGPVL.Entity.Models.Comite;
using MIDIS.SGPVL.Entity.Models.ComitePvl;
using MIDIS.SGPVL.Entity.Models.Maestro;

namespace MIDIS.SGPVL.Entity.Models.Persona
{
    public partial class VLPerNatural
    {
      
        public int iCodPersona { get; set; }
        public string vApePaterno { get; set; }
        public string vApeMaterno { get; set; }
        public string vNombre { get; set; }
        public string vNroDocumento { get; set; }
        public bool? bActivo { get; set; }
        public int iTipDocumento { get; set; }
        public int? bSexo { get; set; }
        public string vTelFijo { get; set; }
        public string vCelular { get; set; }
        public string vEmail { get; set; }
        public string vDireccion { get; set; }
        public string vUbigeo { get; set; }
        public DateTime? dFecNacimiento { get; set; }

        public VLPersona iCodPersonaNavigation { get; set; }
        public VLEnumItem iTipDocumentoNavigation { get; set; }
        public VLEnumItem bSexoNavigation { get; set; }
        public List<VLAdmMiembro> VLAdmMiembros { get; set; }
        public List<VLMiembroJuntum> VLMiembroJunta { get; set; }
        public List<VLSocio> VLSocios { get; set; }
        public List<VLUsuario> VLUsuarios { get; set; }
    }
}