// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MIDIS.SGPVL.Entity.Models.Maestro;

namespace MIDIS.SGPVL.Entity.Models.Persona
{
    public partial class VLPersona
    {
        public int iCodPersona { get; set; }
        public string vNomComercial { get; set; }
        public string vNomCompleto { get; set; }
        public string vRuc { get; set; }
        public bool? bEstado { get; set; }
        public int iTipPersona { get; set; }

        public VLEnumItem iTipPersonaNavigation { get; set; }
        public VLPerNatural VLPerNatural { get; set; }
    }
}