// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MIDIS.SGPVL.Entity.Models.Maestro;

namespace MIDIS.SGPVL.Entity.Models.ComitePvl
{
    public partial class VLComVasoLeche
    {
        public int iCodComVasLeche { get; set; }
        public int iTipOsb { get; set; }
        public int iTipAlimento { get; set; }
        public string vCodComite { get; set; }
        public string vUbigeo { get; set; }
        public int? iCodCentPoblado { get; set; }
        public string vNomComite { get; set; }
        public bool? bActivo { get; set; }
        public int? iNumSocio { get; set; }
        public int? iNumUsuario { get; set; }
        public string vLatitud { get; set; }
        public string vLongitud { get; set; }
        public string vDireccion { get; set; }
        public string vReferencia { get; set; }
        public string vUsuRegistro { get; set; }
        public DateTime? dFecRegistro { get; set; }
        public string vUsuModifica { get; set; }
        public DateTime? dFecModifica { get; set; }

        public VLEnumItem iTipAlimentoNavigation { get; set; }
        public VLEnumItem iTipOsbNavigation { get; set; }
        public List<VLJunDirectiva> VLJunDirectivas { get; set; }
        public List<VLSocio> VLSocios { get; set; }
        public List<VLUsuario> VLUsuarios { get; set; }
    }
}