// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MIDIS.SGPVL.Entity.Models.Maestro;

namespace MIDIS.SGPVL.Entity.Models.ComitePvl
{
    public partial class VLJunDirectiva
    {

        public int iIdJunta { get; set; }
        public int iCodComVasLeche { get; set; }
        public int iTipResolucion { get; set; }
        public string vNumResolucion { get; set; }
        public DateTime dFecEmision { get; set; }
        public DateTime dFecInicio { get; set; }
        public DateTime? dFecFin { get; set; }
        public bool? bVigente { get; set; }
        public string iNumMiembro { get; set; }
        public string vNomArchivo { get; set; }
        public string vNomArcGuid { get; set; }
        public string vObservacion { get; set; }
        public string vUsuRegistro { get; set; }
        public DateTime? dFecRegistro { get; set; }
        public string vUsuModifica { get; set; }
        public DateTime? dFecModifica { get; set; }

        public VLComVasoLeche iCodComVasLecheNavigation { get; set; }
        public VLEnumItem iTipResolucionNavigation { get; set; }
        public List<VLMiembroJuntum> VLMiembroJunta { get; set; }
    }
}