// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MIDIS.SGPVL.Entity.Models.Maestro;
using MIDIS.SGPVL.Entity.Models.Persona;

namespace MIDIS.SGPVL.Entity.Models.ComitePvl
{
    public partial class VLMiembroJuntum
    {
        public int iIdMiembro { get; set; }
        public int iCodPersona { get; set; }
        public int iIdJunta { get; set; }
        public int iTipCargo { get; set; }
        public bool? bActivo { get; set; }
        public string vUsuRegistro { get; set; }
        public DateTime? dFecRegistro { get; set; }
        public string vUsuModifica { get; set; }
        public DateTime? dFecModifica { get; set; }

        public VLPerNatural iCodPersonaNavigation { get; set; }
        public VLJunDirectiva iIdJuntaNavigation { get; set; }
        public VLEnumItem iTipCargoNavigation { get; set; }
    }
}