// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MIDIS.SGPVL.Entity.Models.Maestro;

namespace MIDIS.SGPVL.Contexto.Data.Configurations
{
    public partial class MaeCentroPobladoConfiguration : IEntityTypeConfiguration<MaeCentroPoblado>
    {
        public void Configure(EntityTypeBuilder<MaeCentroPoblado> entity)
        {
            entity.HasKey(e => e.vUbigeo);

            entity.ToTable("MaeCentroPoblado");

            entity.Property(e => e.vUbigeo)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.dtFecIngreso)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(getdate())");

            entity.Property(e => e.vCentroPoblado)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.vDepartamento)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.vDistrito)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.vProvincia)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MaeCentroPoblado> entity);
    }
}
