// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MIDIS.SGPVL.Entity.Models.Maestro;

namespace MIDIS.SGPVL.Contexto.Data.Configurations
{
    public partial class MaeDistritoConfiguration : IEntityTypeConfiguration<MaeDistrito>
    {
        public void Configure(EntityTypeBuilder<MaeDistrito> entity)
        {
            entity.HasKey(e => new { e.vCodigoDepartamento, e.vCodigoProvincia, e.vCodigoDistrito });

            entity.ToTable("MaeDistrito");

            entity.Property(e => e.vCodigoDepartamento)
                .HasMaxLength(2)
                .IsUnicode(false);

            entity.Property(e => e.vCodigoProvincia)
                .HasMaxLength(2)
                .IsUnicode(false);

            entity.Property(e => e.vCodigoDistrito)
                .HasMaxLength(2)
                .IsUnicode(false);

            entity.Property(e => e.dLatitud).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.dLongitud).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.vDescripcion)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.vCodigo)
                .WithMany(p => p.MaeDistritos)
                .HasForeignKey(d => new { d.vCodigoDepartamento, d.vCodigoProvincia })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MaeDistrito_MaeProvincia");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MaeDistrito> entity);
    }
}
