// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MIDIS.SGPVL.Entity.Models.Maestro;

namespace MIDIS.SGPVL.Contexto.Data.Configurations
{
    public partial class MaeDepartamentoConfiguration : IEntityTypeConfiguration<MaeDepartamento>
    {
        public void Configure(EntityTypeBuilder<MaeDepartamento> entity)
        {
            entity.HasKey(e => e.vCodigoDepartamento);

            entity.ToTable("MaeDepartamento");

            entity.Property(e => e.vCodigoDepartamento)
                .HasMaxLength(2)
                .IsUnicode(false);

            entity.Property(e => e.vDescripcion)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MaeDepartamento> entity);
    }
}
