// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MIDIS.SGPVL.Entity.Models.Maestro;

namespace MIDIS.SGPVL.Contexto.Data.Configurations
{
    public partial class MaeProvinciumConfiguration : IEntityTypeConfiguration<MaeProvincium>
    {
        public void Configure(EntityTypeBuilder<MaeProvincium> entity)
        {
            entity.HasKey(e => new { e.vCodigoDepartamento, e.vCodigoProvincia });

            entity.Property(e => e.vCodigoDepartamento)
                .HasMaxLength(2)
                .IsUnicode(false);

            entity.Property(e => e.vCodigoProvincia)
                .HasMaxLength(2)
                .IsUnicode(false);

            entity.Property(e => e.vDescripcion)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.vCodigoDepartamentoNavigation)
                .WithMany(p => p.MaeProvincia)
                .HasForeignKey(d => d.vCodigoDepartamento)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MaeProvincia_MaeDepartamento");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MaeProvincium> entity);
    }
}
