// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MIDIS.SGPVL.Entity.Models.Comite;

namespace MIDIS.SGPVL.Contexto.Data.Configurations
{
    public partial class VLAdmMiembroConfiguration : IEntityTypeConfiguration<VLAdmMiembro>
    {
        public void Configure(EntityTypeBuilder<VLAdmMiembro> entity)
        {
            entity.HasKey(e => e.iIdMiembro)
                .HasName("PK__VLAdmMie__01C359161E8E9A00");

            entity.ToTable("VLAdmMiembro", "Comite");

            entity.Property(e => e.dFecModifica).HasColumnType("datetime");

            entity.Property(e => e.dFecRegistro).HasColumnType("datetime");

            entity.Property(e => e.vOtrCargo)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.vUsuModifica)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.vUsuRegistro)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.iCodPersonaNavigation)
                .WithMany(p => p.VLAdmMiembros)
                .HasForeignKey(d => d.iCodPersona)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VLAdmMiem__iCodP__4865BE2A");

            entity.HasOne(d => d.iIdComiteNavigation)
                .WithMany(p => p.VLAdmMiembros)
                .HasForeignKey(d => d.iIdComite)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VLAdmMiem__iIdCo__4959E263");

            entity.HasOne(d => d.iTipCargoNavigation)
                .WithMany(p => p.VLAdmMiembros)
                .HasForeignKey(d => d.iTipCargo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VLAdmMiem__iTipC__4A4E069C");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VLAdmMiembro> entity);
    }
}
