// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MIDIS.SGPVL.Entity.Models.Comite;

namespace MIDIS.SGPVL.Contexto.Data.Configurations
{
    public partial class VLAdministrativoConfiguration : IEntityTypeConfiguration<VLAdministrativo>
    {
        public void Configure(EntityTypeBuilder<VLAdministrativo> entity)
        {
            entity.HasKey(e => e.iIdComite).HasName("PK__VLAdmini__E67D0430EF054562");
            entity.ToTable("VLAdministrativo", "Comite");
            entity.Property(e => e.dFecEmision).HasColumnType("date");
            entity.Property(e => e.dFecFin).HasColumnType("date");
            entity.Property(e => e.dFecInicio).HasColumnType("date");
            entity.Property(e => e.dFecModifica).HasColumnType("datetime");
            entity.Property(e => e.dFecRegistro).HasColumnType("datetime");
            //entity.Property(e => e.iNumMiembro).IsRequired();
            entity.Property(e => e.vUbigeo).HasMaxLength(30);
            entity.Property(e => e.vNomArcGuid).IsRequired().HasMaxLength(250).IsUnicode(false);
            entity.Property(e => e.vNomArchivo).IsRequired().HasMaxLength(250).IsUnicode(false);
            entity.Property(e => e.vNumResolucion).IsRequired().HasMaxLength(250).IsUnicode(false);
            entity.Property(e => e.vObservacion).HasMaxLength(300).IsUnicode(false);
            entity.Property(e => e.vUsuModifica).HasMaxLength(50).IsUnicode(false);
            entity.Property(e => e.vUsuRegistro).HasMaxLength(50).IsUnicode(false);
            entity.HasOne(d => d.iTipResolucionNavigation)
                .WithMany(p => p.VLAdministrativos)
                .HasForeignKey(d => d.iTipResolucion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VLAdminis__iTipR__477199F1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VLAdministrativo> entity);
    }
}
