// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MIDIS.SGPVL.Entity.Models.Maestro;
namespace MIDIS.SGPVL.Contexto.Data.Configurations
{
    public partial class VLEnumeradoConfiguration : IEntityTypeConfiguration<VLEnumerado>
    {
        public void Configure(EntityTypeBuilder<VLEnumerado> entity)
        {
            entity.HasKey(e => e.iIdEnumerado)
                .HasName("PK__VLEnumer__51FCB01C6FF5BD56");

            entity.ToTable("VLEnumerado", "Maestro");

            entity.Property(e => e.vDesCorto)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.vDesLargo)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.vDescripcion)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.vValor)
                .HasMaxLength(10)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VLEnumerado> entity);
    }
}
