// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MIDIS.SGPVL.Entity.Models.Maestro;
namespace MIDIS.SGPVL.Contexto.Data.Configurations
{
    public partial class VLEnumItemConfiguration : IEntityTypeConfiguration<VLEnumItem>
    {
        public void Configure(EntityTypeBuilder<VLEnumItem> entity)
        {
            entity.HasKey(e => e.iIdEnuItem)
                .HasName("PK__VLEnumIt__6D76B8D8D07C7356");

            entity.ToTable("VLEnumItem", "Maestro");

            entity.Property(e => e.vDesCorto)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.vDesLargo)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.vDescripcion)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.vValor1)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.vValor2)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.vValor3)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.iIdEnumeradoNavigation)
                .WithMany(p => p.VLEnumItems)
                .HasForeignKey(d => d.iIdEnumerado)
                .HasConstraintName("FK__VLEnumIte__iIdEn__44952D46");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VLEnumItem> entity);
    }
}
