// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MIDIS.SGPVL.Entity.Models.ComitePvl;
namespace MIDIS.SGPVL.Contexto.Data.Configurations
{
    public partial class VLJunDirectivaConfiguration : IEntityTypeConfiguration<VLJunDirectiva>
    {
        public void Configure(EntityTypeBuilder<VLJunDirectiva> entity)
        {
            entity.HasKey(e => e.iIdJunta)
                .HasName("PK__VLJunDir__A90D8C9E2469DD55");

            entity.ToTable("VLJunDirectiva", "ComitePvl");

            entity.Property(e => e.dFecEmision).HasColumnType("date");

            entity.Property(e => e.dFecFin).HasColumnType("date");

            entity.Property(e => e.dFecInicio).HasColumnType("date");

            entity.Property(e => e.dFecModifica).HasColumnType("datetime");

            entity.Property(e => e.dFecRegistro).HasColumnType("datetime");

            entity.Property(e => e.iNumMiembro)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.vNomArcGuid)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.vNomArchivo)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.vNumResolucion)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.vObservacion)
                .HasMaxLength(300)
                .IsUnicode(false);

            entity.Property(e => e.vUsuModifica)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.vUsuRegistro)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.iCodComVasLecheNavigation)
                .WithMany(p => p.VLJunDirectivas)
                .HasForeignKey(d => d.iCodComVasLeche)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VLJunDire__iCodC__4D2A7347");

            entity.HasOne(d => d.iTipResolucionNavigation)
                .WithMany(p => p.VLJunDirectivas)
                .HasForeignKey(d => d.iTipResolucion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VLJunDire__iTipR__4E1E9780");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VLJunDirectiva> entity);
    }
}
