// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MIDIS.SGPVL.Entity.Models.ComitePvl;
namespace MIDIS.SGPVL.Contexto.Data.Configurations
{
    public partial class VLMiembroJuntumConfiguration : IEntityTypeConfiguration<VLMiembroJuntum>
    {
        public void Configure(EntityTypeBuilder<VLMiembroJuntum> entity)
        {
            entity.HasKey(e => e.iIdMiembro)
                .HasName("PK__VLMiembr__01C35916C3412683");

            entity.ToTable("VLMiembroJunta", "ComitePvl");

            entity.Property(e => e.dFecModifica).HasColumnType("datetime");

            entity.Property(e => e.dFecRegistro).HasColumnType("datetime");

            entity.Property(e => e.vUsuModifica)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.vUsuRegistro)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.iCodPersonaNavigation)
                .WithMany(p => p.VLMiembroJunta)
                .HasForeignKey(d => d.iCodPersona)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VLMiembro__iCodP__4F12BBB9");

            entity.HasOne(d => d.iIdJuntaNavigation)
                .WithMany(p => p.VLMiembroJunta)
                .HasForeignKey(d => d.iIdJunta)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VLMiembro__iIdJu__5006DFF2");

            entity.HasOne(d => d.iTipCargoNavigation)
                .WithMany(p => p.VLMiembroJunta)
                .HasForeignKey(d => d.iTipCargo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VLMiembro__iTipC__50FB042B");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VLMiembroJuntum> entity);
    }
}
