// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MIDIS.SGPVL.Entity.Models.Persona;
namespace MIDIS.SGPVL.Contexto.Data.Configurations
{
    public partial class VLPerNaturalConfiguration : IEntityTypeConfiguration<VLPerNatural>
    {
        public void Configure(EntityTypeBuilder<VLPerNatural> entity)
        {
            entity.HasKey(e => e.iCodPersona).HasName("PK__VLPerNat__C021D753D7ABB93E");
            entity.ToTable("VLPerNatural", "Persona");
            entity.Property(e => e.iCodPersona).ValueGeneratedNever();
            entity.Property(e => e.dFecNacimiento).HasColumnType("date");
            entity.Property(e => e.vUbigeo).HasMaxLength(30);
            entity.Property(e => e.vApeMaterno).IsRequired().HasMaxLength(100).IsUnicode(false);
            entity.Property(e => e.vApePaterno).IsRequired().HasMaxLength(100).IsUnicode(false);
            entity.Property(e => e.vCelular).HasMaxLength(20).IsUnicode(false);
            entity.Property(e => e.vDireccion).IsRequired().HasMaxLength(250).IsUnicode(false);
            entity.Property(e => e.vEmail).HasMaxLength(50).IsUnicode(false);
            entity.Property(e => e.vNombre).IsRequired().HasMaxLength(100).IsUnicode(false);
            entity.Property(e => e.vNroDocumento).IsRequired().HasMaxLength(9).IsUnicode(false);
            entity.Property(e => e.vTelFijo).HasMaxLength(20).IsUnicode(false);

            entity.HasOne(d => d.iCodPersonaNavigation)
                .WithOne(p => p.VLPerNatural)
                .HasForeignKey<VLPerNatural>(d => d.iCodPersona)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VLPerNatu__iCodP__43A1090D");

            entity.HasOne(d => d.iTipDocumentoNavigation)
                .WithMany(p => p.VLPerNaturals)
                .HasForeignKey(d => d.iTipDocumento)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VLPerNatu__iTipD__467D75B8");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VLPerNatural> entity);
    }
}
