// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MIDIS.SGPVL.Entity.Models.ComitePvl;
namespace MIDIS.SGPVL.Contexto.Data.Configurations
{
    public partial class VLSocioConfiguration : IEntityTypeConfiguration<VLSocio>
    {
        public void Configure(EntityTypeBuilder<VLSocio> entity)
        {
            entity.HasKey(e => e.iIdSocio)
                .HasName("PK__VLSocio__B9B7C2741E858E22");

            entity.ToTable("VLSocio", "ComitePvl");

            entity.Property(e => e.dFecModifica).HasColumnType("datetime");

            entity.Property(e => e.dFecParto).HasColumnType("date");

            entity.Property(e => e.dFecRegistro).HasColumnType("datetime");

            entity.Property(e => e.dFecTermLactancia).HasColumnType("date");

            entity.Property(e => e.vUsuModifica)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.vUsuRegistro)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.iCodComVasLecheNavigation)
                .WithMany(p => p.VLSocios)
                .HasForeignKey(d => d.iCodComVasLeche)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VLSocio__iCodCom__52E34C9D");

            entity.HasOne(d => d.iCodPersonaNavigation)
                .WithMany(p => p.VLSocios)
                .HasForeignKey(d => d.iCodPersona)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VLSocio__iCodPer__51EF2864");

            entity.HasOne(d => d.iTipSocioNavigation)
                .WithMany(p => p.VLSocios)
                .HasForeignKey(d => d.iTipSocio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VLSocio__iTipSoc__53D770D6");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VLSocio> entity);
    }
}
