//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsMigracion
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MigracionesCE_Request", Namespace="http://schemas.datacontract.org/2004/07/APP.GSWEE.Entidades")]
    public partial class MigracionesCE_Request : object
    {
        
        private string ClaveField;
        
        private string NumeroDeDocumentoField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave
        {
            get
            {
                return this.ClaveField;
            }
            set
            {
                this.ClaveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDeDocumento
        {
            get
            {
                return this.NumeroDeDocumentoField;
            }
            set
            {
                this.NumeroDeDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MigracionesCE_Response", Namespace="http://schemas.datacontract.org/2004/07/APP.GSWEE.Entidades")]
    public partial class MigracionesCE_Response : object
    {
        
        private WsMigracion.MigracionesCE_Registro CEDatoField;
        
        private string CodigoField;
        
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WsMigracion.MigracionesCE_Registro CEDato
        {
            get
            {
                return this.CEDatoField;
            }
            set
            {
                this.CEDatoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MigracionesCE_Registro", Namespace="http://schemas.datacontract.org/2004/07/APP.GSWEE.Entidades")]
    public partial class MigracionesCE_Registro : object
    {
        
        private string CalidadMigratoriaField;
        
        private string NombresField;
        
        private string NumeroDocumentoField;
        
        private string PrimerApellidoField;
        
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CalidadMigratoria
        {
            get
            {
                return this.CalidadMigratoriaField;
            }
            set
            {
                this.CalidadMigratoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumento
        {
            get
            {
                return this.NumeroDocumentoField;
            }
            set
            {
                this.NumeroDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellido
        {
            get
            {
                return this.PrimerApellidoField;
            }
            set
            {
                this.PrimerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido
        {
            get
            {
                return this.SegundoApellidoField;
            }
            set
            {
                this.SegundoApellidoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsMigracion.IMigracionesCE_Servicio")]
    public interface IMigracionesCE_Servicio
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMigracionesCE_Servicio/ConsultarPorNumeroDeDocumento", ReplyAction="http://tempuri.org/IMigracionesCE_Servicio/ConsultarPorNumeroDeDocumentoResponse")]
        WsMigracion.ConsultarPorNumeroDeDocumentoResponse ConsultarPorNumeroDeDocumento(WsMigracion.ConsultarPorNumeroDeDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMigracionesCE_Servicio/ConsultarPorNumeroDeDocumento", ReplyAction="http://tempuri.org/IMigracionesCE_Servicio/ConsultarPorNumeroDeDocumentoResponse")]
        System.Threading.Tasks.Task<WsMigracion.ConsultarPorNumeroDeDocumentoResponse> ConsultarPorNumeroDeDocumentoAsync(WsMigracion.ConsultarPorNumeroDeDocumentoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorNumeroDeDocumento", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarPorNumeroDeDocumentoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WsMigracion.MigracionesCE_Request peticion;
        
        public ConsultarPorNumeroDeDocumentoRequest()
        {
        }
        
        public ConsultarPorNumeroDeDocumentoRequest(WsMigracion.MigracionesCE_Request peticion)
        {
            this.peticion = peticion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorNumeroDeDocumentoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarPorNumeroDeDocumentoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WsMigracion.MigracionesCE_Response ConsultarPorNumeroDeDocumentoResult;
        
        public ConsultarPorNumeroDeDocumentoResponse()
        {
        }
        
        public ConsultarPorNumeroDeDocumentoResponse(WsMigracion.MigracionesCE_Response ConsultarPorNumeroDeDocumentoResult)
        {
            this.ConsultarPorNumeroDeDocumentoResult = ConsultarPorNumeroDeDocumentoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IMigracionesCE_ServicioChannel : WsMigracion.IMigracionesCE_Servicio, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class MigracionesCE_ServicioClient : System.ServiceModel.ClientBase<WsMigracion.IMigracionesCE_Servicio>, WsMigracion.IMigracionesCE_Servicio
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MigracionesCE_ServicioClient() : 
                base(MigracionesCE_ServicioClient.GetDefaultBinding(), MigracionesCE_ServicioClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMigracionesCE_Servicio.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MigracionesCE_ServicioClient(EndpointConfiguration endpointConfiguration) : 
                base(MigracionesCE_ServicioClient.GetBindingForEndpoint(endpointConfiguration), MigracionesCE_ServicioClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MigracionesCE_ServicioClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MigracionesCE_ServicioClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MigracionesCE_ServicioClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MigracionesCE_ServicioClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MigracionesCE_ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public WsMigracion.ConsultarPorNumeroDeDocumentoResponse ConsultarPorNumeroDeDocumento(WsMigracion.ConsultarPorNumeroDeDocumentoRequest request)
        {
            return base.Channel.ConsultarPorNumeroDeDocumento(request);
        }
        
        public System.Threading.Tasks.Task<WsMigracion.ConsultarPorNumeroDeDocumentoResponse> ConsultarPorNumeroDeDocumentoAsync(WsMigracion.ConsultarPorNumeroDeDocumentoRequest request)
        {
            return base.Channel.ConsultarPorNumeroDeDocumentoAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMigracionesCE_Servicio))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMigracionesCE_Servicio))
            {
                return new System.ServiceModel.EndpointAddress("http://app_pruebas.midis.gob.pe/Sis_WS/App/MigracionesCE_Servicio.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MigracionesCE_ServicioClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMigracionesCE_Servicio);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MigracionesCE_ServicioClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMigracionesCE_Servicio);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMigracionesCE_Servicio,
        }
    }
}
