// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MIDIS.SGPVL.Entity.Models.Maestro
{
    public partial class MaeCentroPoblado
    {
        public string vDepartamento { get; set; }
        public string vProvincia { get; set; }
        public string vDistrito { get; set; }
        public string vCentroPoblado { get; set; }
        public string vUbigeo { get; set; }
        public bool? bComunidadCampesina { get; set; }
        public bool? bComunidadNativa { get; set; }
        public DateTime? dtFecIngreso { get; set; }
    }
}