// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations.Schema;

namespace MIDIS.SGPVL.Entity.Models.Maestro
{
    public partial class MaeDistrito
    {
        public string vCodigoDepartamento { get; set; }
        public string vCodigoProvincia { get; set; }
        public string vCodigoDistrito { get; set; }
        public string vDescripcion { get; set; }
        public decimal? dLatitud { get; set; }
        public decimal? dLongitud { get; set; }
        public bool bEstado { get; set; }
        public bool? DISTRITO_PRIORIZADO { get; set; }
        public bool? bVRAEM { get; set; }
        public int? iCodAmbito { get; set; }

        public MaeProvincium vCodigo { get; set; }

        #region Extensiones

        [NotMapped]
        public string NombreDpto { get; set; }
        [NotMapped]
        public string NombreDistrito { get; set; }
        [NotMapped]
        public string NombreProvincia { get; set; }
        [NotMapped]
        public string codUbigeoFull { get; set; }

        #endregion
    }
}