// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MIDIS.SGPVL.Entity.Models.Maestro
{
    public partial class ubigeo
    {
        public string cod_dep_inei { get; set; }
        public string desc_dep_inei { get; set; }
        public string cod_prov_inei { get; set; }
        public string desc_prov_inei { get; set; }
        public string cod_ubigeo_inei { get; set; }
        public string desc_ubigeo_inei { get; set; }
        public string cod_dep_reniec { get; set; }
        public string desc_dep_reniec { get; set; }
        public string cod_prov_reniec { get; set; }
        public string desc_prov_reniec { get; set; }
        public string cod_ubigeo_reniec { get; set; }
        public string desc_ubigeo_reniec { get; set; }
        public string cod_dep_sunat { get; set; }
        public string desc_dep_sunat { get; set; }
        public string cod_prov_sunat { get; set; }
        public string desc_prov_sunat { get; set; }
        public string cod_ubigeo_sunat { get; set; }
        public string desc_ubigeo_sunat { get; set; }
    }
}