// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MIDIS.SGPVL.Entity.Models.Comite;
using MIDIS.SGPVL.Entity.Models.ComitePvl;
using MIDIS.SGPVL.Entity.Models.Persona;

namespace MIDIS.SGPVL.Entity.Models.Maestro
{
    public partial class VLEnumItem
    {

        public int iIdEnuItem { get; set; }
        public int? iIdEnumerado { get; set; }
        public string vDescripcion { get; set; }
        public string vDesCorto { get; set; }
        public string vDesLargo { get; set; }
        public string vValor1 { get; set; }
        public string vValor2 { get; set; }
        public string vValor3 { get; set; }
        public bool? bActivo { get; set; }

        public VLEnumerado iIdEnumeradoNavigation { get; set; }
        public List<VLAdmMiembro> VLAdmMiembros { get; set; }
        public List<VLAdministrativo> VLAdministrativos { get; set; }
        public List<VLComVasoLeche> VLComVasoLecheiTipAlimentoNavigations { get; set; }
        public List<VLComVasoLeche> VLComVasoLecheiTipOsbNavigations { get; set; }
        public List<VLJunDirectiva> VLJunDirectivas { get; set; }
        public List<VLMiembroJuntum> VLMiembroJunta { get; set; }
        public List<VLPerNatural> VLPerNaturals { get; set; }
        public List<VLPersona> VLPersonas { get; set; }
        public List<VLSocio> VLSocios { get; set; }
        public List<VLUsuario> VLUsuarios { get; set; }
    }
}